env: prod

postgres:
  host: localhost
  port: 5432
  schema: success_bot
  username: admin
  password: 1111
  database: success-bot

bot:
  api_key: prod_api_key
  timeout: 10s
  languages:
    - en
    - ru
  daily_reward: 1000
  subscribe_channel_id: -1050000500001
  subscribe_channel_url: https://t.me/example_channel

finam:
  token: test_finam_token
  account_id: 3992991