env: test
location: "Europe/Moscow"

postgres:
  host: localhost
  port: 5432
  schema: success_bot
  username: admin
  password: 1111
  database: success-bot

bot:
  api_key: test_api_key
  timeout: 10s
  languages:
    - en
    - ru
  subscribe_channel_id: -1050000500001
  subscribe_channel_url: https://t.me/example_channel